# Site settings
title: SADC CBDC
description:SADC COUNTRIES CBDC
baseurl: "" # The subpath of your site, e.g., /blog (leave empty for root).
url: "https://cbmsa.github.io/cbdcwire/)`" # The base URL of your site.

# Author settings
author: CBMSA
  name: B F MUNERI 
  email: cbdc@mcbsresbank.com

# Build settings
markdown: kramdown
theme: minima # Default theme for Jekyll
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Collections
collections:
  posts:
    output: true

# Defaults
defaults:
  - scope:
      path: "" # An empty string here means all files in the project
    values:
      layout: default
