# Site settings
title: Your Site Title
description: A brief description of your site.
baseurl: "" # The subpath of your site, e.g., /blog (leave empty for root).
url: "https://yourwebsite.com" # The base URL of your site.

# Author settings
author: 
  name: Your Name
  email: your.email@example.com

# Build settings
markdown: kramdown
theme: minima # Default theme for Jekyll
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Collections
collections:
  posts:
    output: true

# Defaults
defaults:
  - scope:
      path: "" # An empty string here means all files in the project
    values:
      layout: default
