name: Deploy to Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload files via SFTP
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_USER: "cbdcwire"
          SSH_HOST: "www.mcbsresbank.com"  # Just the hostname
          SSH_KEY: "${{ secrets.SSH_PRIVATE_KEY }}"
          REMOTE_PATH: "/yar/www/html"